## YAML Template.
name: RunicUniverse
author: runelynx
description: "Bukkit plugin for Runic Universe server."
main: io.github.runelynx.runicuniverse.RunicUniverse
version: 0.1
api-version: 1.14
commands:
   announce:
      description: "Announcement management tool for staff"
      usage: /<command>
      permission: rp.staff.enforcer
      permission-message: "You don't have permission: <permission>"
   censor:
      description: "Chat censorship management tool for staff"
      usage: /<command>
      permission: rp.staff.enforcer
      permission-message: "You don't have permission: <permission>"
   goto:
      description: "Inter-universe travel"
      usage: /<command>
      permission: ru.travel
      permission-message: "You don't have permission: <permission>"
   travel:
      description: "Inter-universe travel"
      usage: /<command>
      permission: ru.travel
      permission-message: "You don't have permission: <permission>"
   evacuate:
      description: "Send everyone to Hub"
      usage: /<command>
      permission: rp.staff.evacuate
      permission-message: "You don't have permission: <permission>"
   runicholo:
      description: "Rune's fancy hologram machine"
      usage: /<command>
      permission: ru.holograms
      permission-message: "You don't have permission: <permission>"
   staffrank:
      description: "Staff rank setting command. Enables auto-promotion on all servers."
      usage: "/<command> playername staffrank/none"
      permission: ru.staffpromotion
      permission-message: "You don't have permission: <permission>"